### ISSUE TITLE
Solicit Feedback, Round 2

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#100]
@kwilcox, @lesserwhirls, @cwardgar, @rsignell-usgs, @gajowi, @ethanrd

There has been a whirlwind of activity since we did the [first round of feedback](https://github.com/Unidata/thredds-docker/issues/34) in terms of [issues](https://github.com/Unidata/thredds-docker/issues?utf8=%E2%9C%93&q=created%3A%3E%3D2016-08-30) and [pull requests](https://github.com/Unidata/thredds-docker/pulls?utf8=%E2%9C%93&q=created%3A%3E%3D2016-08-30).

Some highlights are:
-   The [TDS container](https://hub.docker.com/r/unidata/thredds-docker/) is based off of a [Unidata hardened Tomcat container](https://hub.docker.com/r/unidata/tomcat-docker) which is itself based off of the [canonical Tomcat container](https://hub.docker.com/r/docker/tomcat).
-   We are taking advantage of [Dockerhub automated builds capability](https://hub.docker.com/r/unidata/thredds-docker/builds).
-   Incorporated libnetcdf for [NCSS netCDF4 capability](http://unicloud.westus.cloudapp.azure.com/thredds/catalog/grib/NCEP/GFS/Global_onedeg/latest.html) (browse to the subset service link).
-   Improved [travis configuration](https://github.com/Unidata/thredds-docker/blob/master/.travis.yml) where the running web application is actually tested.
-   Decommissioned `https://hub.docker.com/r/unidata/tds`.
-   Incorporated a [license](https://github.com/Unidata/thredds-docker/blob/master/LICENSE.txt).
-   [5.0-SNAPSHOT branch is available](https://hub.docker.com/r/unidata/thredds-docker/tags/).
- README improvements and clarifications concerning `docker-compose`, etc.

Is there anything we have not covered before we can start advertising this effort? I would also like to find beta testers (you?) willing to tolerate problems if issues should arise. On my end, I need to start doing PR in terms of blog posts, announcements, etc. I'll also be[ presenting this work at the AMS 2017 annual meeting in Seattle](https://ams.confex.com/ams/97Annual/webprogram/Paper315508.html).

**Comment by rsignell-usgs** [comment]
I tried this out with the 5.0-SNAPSHOT and it worked great.    The only thing I would suggest is mounting all the volumes as read-only, except for the log directories.  That way you won't have the problem of all your thredds catalogs owned by someone other than yourself after you launch the container.   You can do this by putting an `:ro` after the volume you are mounting.  Here's my yaml as an example:
```
tds-dev:
  image: unidata/thredds-docker:5.0-SNAPSHOT
  ports:
    - "8080:8080"
    - "443:8443"
    - "8443:8443"
  container_name: tds-dev
  volumes:
    - /opt/docker/tds-dev/tomcat/logs/:/usr/local/tomcat/logs/
    - /opt/docker/tds-dev/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
    - /opt/docker/tds-dev/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
    - /opt/docker/tds-dev/thredds/:/usr/local/tomcat/content/thredds:ro
    - /usgs:/usgs:ro
```
