### ISSUE TITLE
Move cache and logs out of content directory to help permission problems?

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds-docker#158]
I'm having permission problems with volumes.   

I have my `threddsConfig.xml`, `catalog.xml` and other catalogs (.xml) files on my local system located in this content directory:
`/opt/docker/tds/content/thredds`.

I want my catalogs to be read only, but of course the container needs to write to the `logs` and `cache` directories. 

So I tried:
```
  tds:
    image: unidata/thredds-docker:4.6.10
    ports:
      - "8080:8080"
    container_name: tds
    volumes:
      - /opt/docker/tds/content/thredds:/usr/local/tomcat/content/thredds:ro
      - /opt/docker/tds/tomcat/logs:/usr/local/tomcat/logs 
      - /opt/docker/tds/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/
tomcat-users.xml:ro
     - /opt/docker/tds/content/thredds/cache:/usr/local/tomcat/content/thredds/cache
     - /opt/docker/tds/content/thredds/logs:/usr/local/tomcat/content/thredds/logs
```
but docker complains that it can't write to `cache` because it's read only.  And of course it's read only because it's parent, where the catalogs are, is read only.

Could the container be built so that the `logs` and `cache` directories are *NOT* under content?

Or some other solution?

**Comment by julienchastang** [comment]
Instead of trying to solve this issue at the container level, I would try to handle this outside the container at the file system level. What happens if you `chmod` `threddsConfig.xml` and `catalog.xml` to your liking outside the container.

**Comment by rsignell-usgs** [comment]
You mean make sure they are not writable by group on the local machine, and then expect that the container will not be able to write to them. Correct?

**Comment by julienchastang** [comment]
Though, I've encountered *many* Docker gotchas in this area, that is what I would try. The container will respect the `chown` options I believe.

**Comment by rsignell-usgs** [comment]
@julienchastang , I still think the best way to handle this would be to write the `logs` and `cache` directories to a location other than `/usr/local/tomcat/content/thredds`, say like `/thredds/cache` and `/thredds/logs`.  
That way a user could use a `docker-compose.yml` file like:
```
  tds-dev:
    image: unidata/thredds-docker:4.6.10
    ports:
      - "8080:8080"
    container_name: tds
    volumes:
      - /opt/docker/tds/thredds:/usr/local/tomcat/content/thredds:ro
      - /opt/docker/tds/cache:/cache
      - /opt/docker/tds/logs:/logs
      - /opt/docker/tds/tomcat/logs:/usr/local/tomcat/logs
      - /opt/docker/tds/tomcat/conf:/usr/local/tomcat/conf:ro
      - /data:/data:ro
```
and not have problems with permissions.    

This is the way tomcat is set up, why not do the same with thredds?
