### ISSUE TITLE
Docker Swarm "Unable to create file "

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#217]
Posting on behalf of user. Also ping @isuftin.

---

I have successfully run your THREDDS docker container on my local machine. Everything seems fine. However, when I try to run multiple instances in a docker swarm, I have an issue where the containers close every few minutes and re-launch.

I am following the instructions found here:
[https://github.com/Unidata/thredds-docker/blob/master/README_SWARM.md](https://github.com/Unidata/thredds-docker/blob/master/README_SWARM.md)
and I used the `docker-compose-swarm.yml` file that is referred to on that page. 

In addition to those instructions, I have made a number of changes in attempts to get the system working. For example, I have tried removing the `drain` option in the call to set up the manager. I have also tried modifying `docker-compose-swarm.yml` in a variety of ways. When I run `docker ps` on the service, I get the error message:

`task: non-zero exit (143): dockerexec: unhealthy container`

I have pasted the output from docker service logs at the end of this message. Also, after many attempts, I have modified your suggested `docker-compose-swarm.yml` as follows:

```yaml
version: '3.3'

secrets:
  thredds_tomcat_users:
    file: ./tomcat-users.xml

configs:
  thredds_tomcat_users:
    file: ./tomcat-users.xml

networks:
  thredds_network:

volumes:
  thredds_volume:
    labels:
      - "docker.volume.description=THREDDS Docker Volume"
      - "docker.volume.name=volume.thredds"
      - /home/mt/threddstest/:/usr/local/tomcat/logs/
      - /home/mt/threddstest/:/usr/local/tomcat/content/thredds/logs/
      - /home/mt/threddstest/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /home/mt/Desktop/v2_results/holder/:/usr/local/tomcat/content/thredds
      - /home/mt/Desktop/v2_results/holder/:/path/to/your/data/directory1

services:
  thredds:
    image: unidata/thredds-docker:latest
    networks:
        thredds_network:
          aliases:
            - thredds
    volumes:
      - "thredds_volume:/usr/local/tomcat/logs/"
      - "thredds_volume:/usr/local/tomcat/content/thredds/logs/"
      - "thredds_volume:/usr/local/tomcat/conf/Catalina/localhost"
      - "thredds_volume:/usr/local/tomcat/work/Catalina/localhost/thredds"
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    env_file:
      - "swarm_compose.env"
    secrets:
      - source: thredds_tomcat_users
        target: /usr/local/tomcat/conf/tomcat-users.xml
        uid: '1000'
    healthcheck:
      test: "NONE"
```

Really, I have two questions:

1. I want to put a THREDDS server on an amazon ec2 instance. How much traffic / use  is a single docker container able to handle? In other words, is it necessary for me to set up a docker swarm or can I just use the single docker container version that is already working on my laptop?

2. What am I doing wrong? Please see the logs below. The errors seem to indicate that THREDDS cannot access the file system outside the docker containers. For example:
`ERROR Unable to create file /home/mt/Desktop/v2_results/holder///thredds/logs/threddsServlet.log java.io.IOException: Could not create directory /home/mt/Desktop/v2_results/holder/thredds/logs`
and `localhost-startStop-1 ERROR Unable to locate appender "catalogInit" for logger config`

I have tried to creating the local folders referenced in the above `docker-compose-swarm.yml` file on each of the docker containers in the swarm. That does not help either.

I am excited to use the THREDDS server. It is a great piece of software. Any help you can offer would be greatly appreciated.

Here is the output of the docker service logs:

`task: non-zero exit (143): dockerexec: unhealthy container`

[The full log is captured in this gist](https://gist.github.com/julienchastang/67b247d7c98cbc57de02d4296472540f)
