### ISSUE TITLE
Cant get thredds-production to work, quickstart works though

### ISSUE THREAD

**Issue by deadpickle** [Unidata/thredds-docker#257]
- thredds-docker 5.0
- Ubuntu 20.04

When I run `docker run -d -p 80:8080 unidata/thredds-docker` I can access the test catalog but when I run `docker-compose run -d thredds-production` the container fails stating `Caused by: java.lang.IllegalStateException: Content root directory [/extdata/tomcat/content/thredds] not a directory`

I'm not sure why this is occurring. The contents of `docker_local.env` is:
`TDS_CONTENT_ROOT_PATH=/extdata/tomcat/content/thredds`

The `docker-compose.yml`:
```
thredds-production:
    image: unidata/thredds-docker:5.0
    ports:
      - "80:8080"
      - "433:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - /extdata/tomcat/logs/:/usr/local/tomcat/logs/
      - /extdata/tomcat/content/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
      - /extdata/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /extdata/tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /extdata/thredds-data:/path/to/your/data/directory1
      - /extdata/thredds-data:/path/to/your/data/directory2
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
```
The folders the log is erroring are, in fact, directories:
```
ls -l /extdata/tomcat/content/
total 0
drwxrwxr-x 3 user docker 55 Dec  9 21:33 thredds
user@server:/extdata/thredds-docker$
```

**Comment by julienchastang** [comment]
I think this has to do with the [upgrade to TDS version 5](https://docs.unidata.ucar.edu/tds/5.1/userguide/upgrade.html). See the 3rd bullet point under Requirements. Theoretically, it should be `/extdata/tomcat/content/` not `/extdata/tomcat/content/thredds`. So in your `docker-compose.yml`:

```- /extdata/tomcat/content/thredds:/usr/local/tomcat/content/```

Same for your `TDS_CONTENT_ROOT_PATH ` (e.g., `/usr/local/tomcat/content/`)

Note, I did not change the directory **outside** the container. Can you give that a shot and let me know what happens?

**Comment by deadpickle** [comment]
So here are the setting that are working (all my directories are outide the container which is at /exdata/thredds-docker, hope thats what you meant):

- `TDS_CONTENT_ROOT_PATH=/usr/local/tomcat/content`
-  `/extdata/tomcat/content/thredds:/usr/local/tomcat/content/thredds`
but I get the same "directory does not exist" error when I set the datasetScan location to another directory `/extdata/thredds-data/`

**Comment by deadpickle** [comment]
Thanks for the reply. Here are my files.
`docker-compose.xml`

```
  thredds-production:
    image: unidata/thredds-docker:5.0
    ports:
      - "8081:8080"
      - "8433:8443"
    container_name: thredds
    volumes:
      - /extdata/tomcat/logs/:/usr/local/tomcat/logs/
      - /extdata/tomcat/content/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
      - /extdata/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /extdata/tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /extdata/thredds-data:/data
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
```

`compose_local.xml`

```
### THREDDS related environment variables

# TDS Content root

TDS_CONTENT_ROOT_PATH=/usr/local/tomcat/content/
```

`catalog.xml`

```
<datasetScan name="AWDN Test" ID="awdntest" path="awdn" location="/data">
    <metadata inherited="true">
      <serviceName>wms</serviceName>
    </metadata>
  </datasetScan>
```

I'm still getting an error in catalogInit.log:
`ERROR: directory /data does not exist`
