### ISSUE TITLE
TDM errors on startup

### ISSUE THREAD

**Issue by cbcunc** [Unidata/thredds-docker#275]
```
$ cat /etc/redhat-release
AlmaLinux release 9.1 (Lime Lynx)
$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:35 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:32 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
$ grep "image:" docker-compose.yml
    image: unidata/thredds-docker:5.3
    image: unidata/tdm-docker:latest
$ docker logs tdm
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
contentDir=/usr/local/tomcat/content
catalog=/usr/local/tomcat/content/thredds/catalog.xml
Server added http://[redacted.org]/
Exception in thread "main" java.lang.NullPointerException
	at thredds.util.ThreddsConfigReader.getRootList(ThreddsConfigReader.java:66)
	at thredds.tdm.Tdm.init(Tdm.java:171)
	at thredds.tdm.Tdm.main(Tdm.java:559)
$
```

**Comment by tdrwenski** [comment]
Hi, thanks for reporting this issue. It looks like there is a problem reading `threddsConfig.xml`.

Can you share your `serverStartup.log`? If you mount a log directory (as is shown in the default docker-compose file) it should be in the mounted directory, otherwise they may need to be copied out of the container.

Could you also share your docker-compose file (or at least the parts without sensitive info)?

**Comment by cbcunc** [comment]
[serverStartup.log](https://github.com/Unidata/thredds-docker/files/11004714/serverStartup.log)

[docker-compose.txt](https://github.com/Unidata/thredds-docker/files/11004768/docker-compose.txt)

docker-compose.yml was changed to docker.compose.txt so it would upload to GitHub.

**Comment by julienchastang** [comment]
Hi Chris. Thanks for this information. The THREDDS Data Manager (TDM) creates indexes for GRIB featureCollections, in a process separate from the TDS.  It is a specialized utility typically employed in scenarios where the TDS is serving real-time data from the Unidata IDD (e.g., GFS Quarter Degree Analysis). I **suspect**  that may not be your intention (correct me if I am wrong!) so you may be able to delete or comment out that section of the `docker-compose.yml` file.  Please let us know if you run into additional problems.

```yaml
version: '3'

services:

  thredds-production:
    image: unidata/thredds-docker:5.3
    ports:
      - "8080:8080"
      - "8443:8443"
    container_name: thredds
    volumes:
      - /var/local/tomcat/conf/:/usr/local/tomcat/conf/
      - /var/local/tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /var/local/tomcat/javaUtilPrefs:/usr/local/tomcat/javaUtilPrefs
      - /var/local/tomcat/logs/:/usr/local/tomcat/logs/
      - /var/local/tomcat/webapps/thredds/:/usr/local/tomcat/webapps/thredds/
      - /projects/csi:/projects/csi
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  # tdm:
  #   image: unidata/tdm-docker:latest
  #   container_name: tdm
  #   volumes:
  #     - /var/local/tomcat/conf/:/usr/local/tomcat/conf/
  #     - /var/local/tomcat/content/thredds:/usr/local/tomcat/content/thredds
  #     - /var/local/tomcat/javaUtilPrefs:/usr/local/tomcat/javaUtilPrefs
  #     - /var/local/tomcat/logs/:/usr/local/tomcat/logs/
  #     - /var/local/tomcat/webapps/thredds/:/usr/local/tomcat/webapps/thredds/
  #     - /projects/csi:/projects/csi
  #   env_file:
  #     - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
```
