### ISSUE TITLE
Running thredds-docker

### ISSUE THREAD

**Issue by lucapaganotti** [Unidata/thredds-docker#295]
* the version of the software with which you are encountering an issue
thredds-docker 5.4

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
trying to deploy in a swarm cluster with ```Docker version 18.09.14, build ca12571```

node OS
``` CentOS Linux release 7.9.2009 (Core)```

kernel version
``` 
[dockadmin@arpav-dckmstr1 thredds-docker]$ uname -a
Linux arpav-dckmstr1.arpa.local 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* a description of the issue with the steps needed to reproduce it
I have tried to run a simple container on a cluster master node issuing ```docker-compose up -d thredds-production```

and getting these docker logs
```
Cannot find /usr/local/tomcat/bin/setclasspath.sh
This file is needed to run this program
```
The displayed log also suggest, as I am in a swarm, to use docker stack deploy

```
[dockadmin@arpav-dckmstr1 thredds-docker]$ docker-compose up -d thredds-production
WARNING: The THREDDS_COMPOSE_ENV_LOCAL variable is not set. Defaulting to a blank string.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating thredds ... done
```

using stack deploy seems to be not mandatory, anyway I also did a stack deploy, but I'm getting the same results controlling logs in the UCP interface.

Have any hint about this? Am I missing something?

Thanks for your answer.

**Comment by julienchastang** [comment]
Pull the latest image again. This will ensure that you have the most recent version.

```
docker pull unidata/thredds-docker:5.4
```

Try again. Does the problem persist? If yes, try running the Docker container with an interactive shell so that you can inspect the file system inside the container. 

```
docker run -it unidata/thredds-docker:5.4 /bin/bash
```

Navigate to the `/usr/local/tomcat/bin/` directory and check if `setclasspath.sh` is present.

Also, in your configuration, I wonder if you are mounting over the `/usr/local/tomcat/bin/` directory. For example, in your Docker Compose file, do you have something like:

```
  thredds:
    volumes:
      - ./local-dir:/usr/local/tomcat/bin
```

?

**Comment by lucapaganotti** [comment]
Hi @julienchastang,

thank you for your answer, checking the image contents reveals that ```setclasspath.sh``` file is where it has to be i.e inside ```/usr/local/tomcat/bin.```.

Anyway I do not exlìplicitly mount ```/usr/local/tomcat/bin``` in my ```docker-compose.yml``` file as a volume.

Here it is my ```docker-compose.yml``` file:

```
version: '3'

services:
  thredds-quickstart:
    image: unidata/thredds-docker:5.4
    ports:
      - "8088:8080"
      - "9443:8443"
      - "10443:8443"

  thredds-production:
    image: unidata/thredds-docker:5.4
    ports:
      - "8088:8080"
      - "9443:8443"
      - "10443:8443"
    container_name: thredds
    volumes:
      - /mnt/nfs_share/thredds/tomcat/logs:/usr/local/tomcat/logs/
      - /mnt/nfs_share/thredds/tomcat/thredds/logs:/usr/local/tomcat/content/thredds/logs/
      - /mnt/nfs_share/thredds/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - /mnt/nfs_share/thredds/tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /mnt/nfs_share/thredds/data/arpa:/usr/share/thredds/data/arpa
      # - /path/to/your/data/directory2:/path/to/your/data/directory2
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  tdm:
    image: unidata/tdm-docker:latest
    container_name: tdm
    volumes:
      - /mnt/nfs_share/thredds/tomcat/content/thredds:/usr/local/tomcat/content/thredds
      - /mnt/nfs_share/thredds/data/arpa:/usr/share/thredds/data/arpa
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
```

as you can see I'm declaring some binding volume but towards this container image folders/files:
* /usr/local/tomcat/logs/
* /usr/local/tomcat/content/thredds/logs/
* /usr/local/tomcat/conf/tomcat-users.xml
* /usr/local/tomcat/content/thredds
as it was in the github docker-compose.yml file in which I changed only the mounted path on the host machine.

If I issue

```
$ docker-compose up thredds-production
```

I get

```
[dockadmin@arpav-dckmstr1 thredds-docker]$ docker-compose up thredds-production
WARNING: The THREDDS_COMPOSE_ENV_LOCAL variable is not set. Defaulting to a blank string.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating thredds ... done
Attaching to thredds
thredds               | Cannot find /usr/local/tomcat/bin/setclasspath.sh
thredds               | This file is needed to run this program
thredds exited with code 1
[dockadmin@arpav-dckmstr1 thredds-docker]$ 
```
Any other hint?

I think I have to change my binding volumes, maybe I need only tomcat-users.xml and my data directory.

Thanks again, have a nice day.

-- lp
