### ISSUE TITLE
dropped ssl support

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#74]
with "migrating to unidata/tomcat-docker:8" ssl support has been dropped.  Is this intentional?

**Comment by julienchastang** [comment]
@gajowi Thanks as always for your helpful input. The Axiom Tomcat container was bundled with a self-signed certificate. While I am not a security expert this seemed to me to not be the best security practice. However, installing your own (self-signed) certificate with the [Unidata Tomcat container](https://github.com/Unidata/tomcat-docker) is not too difficult.

For example, generate your certificate with `openssl`:

```sh
openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=US/ST=Colorado/L=Boulder/O=Unidata/CN=tomcat.example.com" -keyout ./ssl.key -out ./ssl.crt
```

Augment a `server.xml` with:

```xml
<Connector port="8443"
       maxThreads="150"
       enableLookups="false"
       disableUploadTimeout="true"
       acceptCount="100"
       scheme="https"
       secure="true"
       SSLEnabled="true"
       SSLCertificateFile="${catalina.base}/conf/ssl.crt"
       SSLCertificateKeyFile="${catalina.base}/conf/ssl.key" />
```

Then have a `docker-compose.yml` that looks like:

```yaml
thredds-production:
  image: unidata/thredds-docker:4.6.6
  ports:
    - "80:8080"
    - "443:8443"
    - "8443:8443"
  container_name: thredds
  volumes:
    - ~/logs/tds-tomcat/:/usr/local/tomcat/logs/
    - ~/logs/tds/:/usr/local/tomcat/content/thredds/logs/
    - ./files/ssl.crt:/usr/local/tomcat/conf/ssl.crt
    - ./files/ssl.key:/usr/local/tomcat/conf/ssl.key
    - ./files/server.xml:/usr/local/tomcat/conf/server.xml
    - ./files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /data/:/data/
    - ~/tdsconfig/:/usr/local/tomcat/content/thredds
```

What I could do is provide some niceties to make this easier. For example, provide a `server.xml` in the `thredds-docker` repository that is "SSL ready" that could be easily mounted inside the container.

Opinions?
